services:
  gitlab-runner:
    image: gitlab/gitlab-runner:latest
    restarts: unless-stopped
    resatrs: always

    volumes:
      - ./config:/etc/gitlab-runner
      - gitlab_runner_cache:/cache
      - /var/run/docker.sock:/var/run/docker.sock

volumes:
  gitlab_runner_cache: